<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Key' => 'Prístupový kľúč',
    'Address' => 'Adresa',
    'City' => 'Mesto',
    'Country' => 'Krajina',
    'Create Request' => 'Vytvoriť požiadavku',
    'Created At' => 'Dátum vytvorenia',
    'Email' => 'Email',
    'First Name' => 'Krstné meno',
    'Hungarian' => 'Maďarský',
    'ID' => 'ID',
    'Language' => 'Jazyk',
    'Last Name' => 'Priezvisko',
    'Message 1' => 'Správa',
    'Phone' => 'Telefón',
    'Please don`t play with this, don`t send false requests' => 'S tým nehrajte, neposielajte falošné žiadosti',
    'Requests' => 'Žiadosti',
    'Save' => 'Uložiť',
    'Search' => 'Vyhľadávanie',
    'Slovak' => 'Slovenský',
    'Status' => 'Stav',
    'The requested page does not exist.' => 'Požadovaná stránka neexistuje.',
    'Type' => 'Typ',
    'Uid' => 'Uid',
    'Update' => 'Zmeniť',
    'Update Request' => 'Upraviť žiadosť',
    'Updated At' => 'Dátum aktualizácie',
    'You don`t have access to edit this item' => 'Nemáte prístup k úprave tejto položky',
    'Age' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar Url' => '',
    'Create Volunteer' => '',
    'Delete' => '',
    'Facebook Profile Url' => '',
    'Full Name' => '',
    'Message 2' => '',
    'Message 3' => '',
    'Message 4' => '',
    'Reset' => '',
    'Sex' => '',
    'Update Volunteer: {name}' => '',
    'User ID' => '',
    'Volunteers' => '',
    'Click here to see the help requests' => '@@Kliknutím sem zobrazíte žiadosti o pomoc@@',
    'Do you want to help?' => '@@Chcete pomôcť?@@',
    'Help me buying stuff' => '@@Pomôžte mi kúpiť potraviny@@',
    'How can we help?' => '@@Ako môžeme pomôcť?@@',
    'My requests' => '@@Moje žiadosti@@',
];
