<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Key' => 'Hozzáférési kulcs',
    'Address' => 'Cím',
    'City' => 'Város',
    'Country' => 'Ország',
    'Create Request' => 'Segítségkérés létrehozása',
    'Created At' => 'Létrehozva',
    'Email' => 'E-mail cím',
    'First Name' => 'Keresztnév',
    'Full Name' => 'Teljes név',
    'Hungarian' => 'Magyar',
    'ID' => 'ID',
    'Language' => 'Nyelv',
    'Last Name' => 'Vezetéknév',
    'Message 1' => 'Üzenet',
    'Phone' => 'Telefon',
    'Please don`t play with this, don`t send false requests' => 'Kérlek használd felelősségel az oldalt és ne küldj hamis segítségkéréseket',
    'Requests' => 'Kérelmek',
    'Save' => 'Mentés',
    'Search' => 'Kereső',
    'Slovak' => 'Szlovák',
    'Status' => 'Státusz',
    'The requested page does not exist.' => 'A keresett oldal nem található',
    'Update' => 'Frissítés',
    'Update Request' => 'Bejegyzés módosítása',
    'Updated At' => 'Frissítve ekkor',
    'You don`t have access to edit this item' => 'Nincs hozzáférése a bejegyzés szerkesztéséhez',
    'Age' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar Url' => '',
    'Create Volunteer' => 'Önkéntes létrehozása',
    'Delete' => '',
    'Facebook Profile Url' => '',
    'Message 2' => '',
    'Message 3' => '',
    'Message 4' => '',
    'Reset' => '',
    'Sex' => '',
    'Type' => '',
    'Uid' => '',
    'Update Volunteer: {name}' => '',
    'User ID' => '',
    'Volunteers' => '',
    'Click here to see the help requests' => '@@Ide kattintással megjenítteti az eddig kért segítségeket@@',
    'Do you want to help?' => '@@Szeretnél segíteni?@@',
    'Help me buying stuff' => '@@Segíts nekem bevásárolni@@',
    'How can we help?' => '@@Hogyan tudnánk segíteni?@@',
    'My requests' => '@@Saját segítségkéréseim@@',
];
