<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Key' => 'Hozzáférési kulcs',
    'Address' => 'Cím',
    'City' => 'Város',
    'Click here to see the help requests' => 'Ide kattintással megjenítteti az eddig kért segítségeket',
    'Country' => 'Ország',
    'Create Request' => 'Kérelem készítése',
    'Created At' => 'Készítés időpontja',
    'Do you want to help?' => 'Szeretnél segíteni?',
    'Email' => 'E-mail cím',
    'First Name' => 'Keresztnév',
    'Full Name' => 'Teljes név',
    'Help me buying stuff' => 'Segíts nekem bevásárolni',
    'How can we help?' => 'Hogyan tudnánk segíteni?',
    'ID' => 'ID',
    'Last Name' => 'Vezetéknév',
    'Message 1' => 'Megjegyzés',
    'Message 2' => '',
    'Message 3' => '',
    'Message 4' => '',
    'My requests' => 'Saját kérelmeim',
    'Phone' => 'Telefon',
    'Please don`t play with this, don`t send false requests' => 'Kérem ne játszon ezzel, ne küldjön nem valós kérelmeket',
    'Requests' => 'Kérelmek',
    'Reset' => '',
    'Save' => 'Mentés',
    'Search' => 'Kereső',
    'Status' => 'Státusz',
    'The requested page does not exist.' => 'A kért oldal nem elérhető',
    'Type' => '',
    'Uid' => '',
    'Update' => 'Frissítés',
    'Update Request' => 'Kérelem frissítés',
    'Updated At' => 'Frissítve ekkor',
    'You don`t have access to edit this item' => 'Nincs hozzáférése a kérelem szerkesztéséhez',
];
