<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Key' => '',
    'Address' => '',
    'Age' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar Url' => '',
    'City' => '',
    'Country' => '',
    'Create Request' => '',
    'Create Volunteer' => '',
    'Created At' => '',
    'Delete' => '',
    'Email' => '',
    'Facebook Profile Url' => '',
    'First Name' => '',
    'Full Name' => '',
    'Hungarian' => '',
    'ID' => '',
    'Language' => '',
    'Last Name' => '',
    'Message 1' => '',
    'Message 2' => '',
    'Message 3' => '',
    'Message 4' => '',
    'Phone' => '',
    'Please don`t play with this, don`t send false requests' => '',
    'Requests' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Sex' => '',
    'Slovak' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Type' => '',
    'Uid' => '',
    'Update' => '',
    'Update Request' => '',
    'Update Volunteer: {name}' => '',
    'Updated At' => '',
    'User ID' => '',
    'Volunteers' => '',
    'You don`t have access to edit this item' => '',
    'Click here to see the help requests' => '@@@@',
    'Do you want to help?' => '@@@@',
    'Help me buying stuff' => '@@@@',
    'How can we help?' => '@@@@',
    'My requests' => '@@@@',
];
